#!/usr/bin/env node
// Emits src/enums.generated.ts from schemas/enums.schema.json.
//
// Reads the LOCAL mirror, not docs/specs/schemas/: turbo's `inputs` are
// package-relative, so a cross-package read would leave turbo's hash blind to
// schema edits and serve a stale file on a cache hit. The mirror is proven
// byte-identical by eval/harness/tests/unit/test_schema_mirrors.py.
//
// Only closed enums (a `$def` with an `enum` array) are emitted. Open enums use
// `examples` and the *_recommended naming convention; they stay `string`.
// Enums defined inline in research.schema.json rather than here — experience_level,
// subscription, evaluation_* — stay hand-written in index.ts.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const schemaPath = join(pkgRoot, 'schemas', 'enums.schema.json')
const outPath = join(pkgRoot, 'src', 'enums.generated.ts')

const pascal = (s) => s.split('_').map((p) => p[0].toUpperCase() + p.slice(1)).join('')

/** `'a' | 'b'` on one line, or one value per line once it would run long. */
function union(values) {
  const oneLine = values.map((v) => `'${v}'`).join(' | ')
  if (oneLine.length <= 76) return ` ${oneLine}`
  return `\n  | ${values.map((v) => `'${v}'`).join('\n  | ')}`
}

const schema = JSON.parse(readFileSync(schemaPath, 'utf8'))
const defs = schema.$defs ?? {}

const blocks = []
for (const [name, def] of Object.entries(defs)) {
  if (!Array.isArray(def.enum)) continue
  const jsdoc = typeof def.description === 'string'
    ? `/** ${def.description.replace(/\s+/g, ' ').trim()} */\n`
    : ''
  blocks.push(`${jsdoc}export type ${pascal(name)} =${union(def.enum)}`)
}

if (blocks.length === 0) {
  throw new Error(`[gen-enums] no closed enums found in ${schemaPath} — refusing to write an empty file`)
}

const header = `// AUTOGENERATED — do not edit by hand.
// Source: packages/schema/schemas/enums.schema.json
// Regenerated automatically by \`pnpm build\` / \`pnpm typecheck\` in this package.

`

writeFileSync(outPath, header + blocks.join('\n\n') + '\n', 'utf8')
console.log(`[gen-enums] wrote src/enums.generated.ts — ${blocks.length} closed enums`)
