// Emits src/enums.generated.ts from schemas/enums.schema.json.
//
// Reads the LOCAL mirror, not docs/specs/schemas/: turbo's `inputs` are
// package-relative, so a cross-package read would leave turbo's hash blind to
// schema edits and serve a stale file on a cache hit. The mirror is proven
// byte-identical by eval/harness/tests/unit/test_schema_mirrors.py.
//
// Only closed enums (a `$def` with an `enum` array) are emitted. Open enums use
// `examples` and the *_recommended naming convention; they stay `string`.
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const schemaPath = join(pkgRoot, 'schemas', 'enums.schema.json')
const outPath = join(pkgRoot, 'src', 'enums.generated.ts')

export const pascal = (s) =>
  s
    .split('_')
    .map((p) => {
      if (!p) throw new Error(`[gen-enums] cannot PascalCase "${s}" — empty path segment`)
      return p[0].toUpperCase() + p.slice(1)
    })
    .join('')

/** `'a' | 'b'` on one line, or one value per line once it would run long. */
function union(values) {
  for (const v of values) {
    // Emitted inside single quotes; a quote or backslash would produce TS that
    // does not parse, or worse, one that parses into a different union.
    if (/['\\]/.test(v)) {
      throw new Error(`[gen-enums] enum value ${JSON.stringify(v)} contains a quote or backslash`)
    }
  }
  const oneLine = values.map((v) => `'${v}'`).join(' | ')
  if (oneLine.length <= 76) return ` ${oneLine}`
  return `\n  | ${values.map((v) => `'${v}'`).join('\n  | ')}`
}

/** The TS blocks for every closed enum in a parsed enums.schema.json. */
export function renderEnums(schema) {
  const blocks = []
  const emitted = new Set()
  for (const [name, def] of Object.entries(schema.$defs ?? {})) {
    if (!Array.isArray(def.enum)) continue
    emitted.add(pascal(name))
    const jsdoc =
      typeof def.description === 'string'
        ? `/** ${def.description.replace(/\s+/g, ' ').trim()} */\n`
        : ''
    blocks.push(`${jsdoc}export type ${pascal(name)} =${union(def.enum)}`)
  }
  return { blocks, emitted }
}

/**
 * Generated names that `src/index.ts` also declares or re-exports.
 *
 * index.ts re-exports the generated file with `export *`, and a local
 * declaration silently SHADOWS a star-export rather than colliding with it:
 * tsc reports nothing, and consumers get the local one. That is how a generated
 * `ExternalSite` union sat unreachable behind an interface of the same name.
 *
 * Matched loosely on purpose — `\s+` rather than a literal space so a wrapped
 * declaration still counts, and `export { X as Y }` too, since an alias shadows
 * exactly the same way. A miss here is invisible by construction, so the regex
 * is the whole guard.
 */
export function findShadowed(emitted, indexSource) {
  const declared = new Set()
  for (const m of indexSource.matchAll(/^export\s+(?:declare\s+)?(?:interface|type)\s+(\w+)/gm)) {
    declared.add(m[1])
  }
  for (const block of indexSource.matchAll(/^export\s*\{([^}]*)\}/gm)) {
    for (const clause of block[1].split(',')) {
      const alias = /(?:\bas\s+)?(\w+)\s*$/.exec(clause.trim())
      if (alias) declared.add(alias[1])
    }
  }
  return [...emitted].filter((n) => declared.has(n))
}

function main() {
  const schema = JSON.parse(readFileSync(schemaPath, 'utf8'))
  const { blocks, emitted } = renderEnums(schema)

  if (blocks.length === 0) {
    throw new Error(`[gen-enums] no closed enums found in ${schemaPath} — refusing to write an empty file`)
  }

  const indexPath = join(pkgRoot, 'src', 'index.ts')
  if (existsSync(indexPath)) {
    const shadowed = findShadowed(emitted, readFileSync(indexPath, 'utf8'))
    if (shadowed.length > 0) {
      throw new Error(
        `[gen-enums] ${shadowed.join(', ')} would be generated AND declared in src/index.ts. ` +
          `\`export *\` shadows silently, so consumers would get the hand-written one. ` +
          `Rename the declaration in index.ts (prefer matching its research.schema.json $def name).`,
      )
    }
  }

  const header = `// AUTOGENERATED — do not edit by hand.
// Source: packages/schema/schemas/enums.schema.json
// Regenerated automatically by \`pnpm build\` / \`pnpm typecheck\` in this package.

`

  writeFileSync(outPath, header + blocks.join('\n\n') + '\n', 'utf8')
  console.log(`[gen-enums] wrote src/enums.generated.ts — ${blocks.length} closed enums`)
}

// Importable for tests (gen-enums-guards.test.ts) without running the generator.
if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) main()
